### ISSUE TITLE
OLAP4J and iText versions unavailable on repositories

### ISSUE THREAD

**Issue by WLash** [Jaspersoft/jasperreports#13]
Is there a reason why JasperReports depends on libraries which are not available on any repository? Because of the build errors that occur due to this dependencies I've to exclude these libraries and add their nearest relatives from the JasperReports-Repository (http://jasperreports.sourceforge.net/maven2). This problem exists for the iText and the olap4j library. iText depends on a 2.1.7.js6 where only a SNAPSHOT-version exists for. Olap4j depends on version 0.9.7.309-JS-3 where I only can find the version 0.9.7.145. 
Maybe I'm just blind and can't find a repository which provides them. This problem exists since a few versions, so I'm not sure if it's my fault or just was overseen.
JasperReports works fine with the alternatives but it blows up gradle build files in our projects a bit.

**Comment by teodord** [comment]
Our SF.net based Maven repository is obsolete for sometime now. Instead, we published all third party dependencies required by JR Lib on our Maven repo at jfrog.io.
This repository is mentioned in the pom.xml of the JR Lib artifact:

https://jaspersoft.jfrog.io/jaspersoft/list/third-party-ce-artifacts/com/lowagie/itext/2.1.7.js6/

I hope this helps.
Teodor
