### ISSUE TITLE
Getting "PatchedPdfLibraryUnavailableException" after upgrading to jasperreports-6.20.5/6

### ISSUE THREAD

**Issue by tuspatil1** [Jaspersoft/jasperreports#395]
Hi Team/Lucian,

We are upgrading to jasperreports-6.20.6 & we have OpenPDF & FOP libraries in our classpath.
We found that we are getting the below exception:
_**net.sf.jasperreports.export.pdf.classic.PatchedPdfLibraryUnavailableException: FOP glyph substitution is disabled, but patched library not detected. See the Javadoc for more details.**_

As per javadoc, below are two solutions:
1) Set proprty "net.sf.jasperreports.export.pdf.classic.fop.glyph.substitution.enabled" as "true".
- If we select this option, then will functionality work the same as earlier, like jasperreports-6.20.3 and before?

2) Deploy the patched version of the OpenPDF library.
- What does a patched version mean? Is the OpenPDF library modified or patched by Jaspersoft to achieve something?

Thanks,
Tushar

**Comment by dadza** [comment]
1. No, glyph substitutions can result in modified PDF documents.
2. Yes, it's a OpenPDF modified by Jaspersoft to allow disabling glyph substitutions.  The current version is [1.3.30.jaspersoft.3](https://jaspersoft.jfrog.io/third-party-ce-artifacts/com/github/librepdf/openpdf/1.3.30.jaspersoft.3/)

[See the Javadoc for more details.](https://jasperreports.sourceforge.net/api/net/sf/jasperreports/export/pdf/classic/PatchedPdfLibraryUnavailableException.html)

Regards,
Lucian

**Comment by tuspatil1** [comment]
Hi Lucian,

Thanks for your response.
Is there any solution available so the functionality will work the same as earlier, like jasperreports-6.20.3 and before?

We already have one OpenPDF library in our environment, and we **can not** replace it with Jaspersoft's patched OpenPDF; otherwise, it may impact other applications. Also, it will be a concern for maintainability.

Your early response will be helpful.

Thanks,
Tushar

**Comment by tuspatil1** [comment]
Hi Lucian,

Can you please suggest.

Thanks,
Tushar

**Comment by dadza** [comment]
If you don't want to use the Jaspersoft OpenPDF version, what you can do is to set the net.sf.jasperreports.export.pdf.classic.fop.glyph.substitution.enabled property to true, and in addition set the net.sf.jasperreports.export.pdf.classic.document.language property to a value that ensures that no actual glyph substitution is performed.  Not sure though what that value would be, maybe the [OpenPDF documentation would help](https://github.com/LibrePDF/OpenPDF/blob/0c9c4ca393b01444b7cb13bb1d12da202bd0d458/openpdf/src/main/java/com/lowagie/text/Document.java#L206).

Regards,
Lucian

**Comment by tuspatil1** [comment]
Hi Lucian

As per below link, if we upgrade to **OpenPDF 1.3.32**, then we don't need patched version of OpenPDF. Right?
[https://github.com/TIBCOSoftware/jasperreports/issues/398](url)

If yes, is this applicable to community & commercial version 6.21.0?

Thanks,
Tushar
