### ISSUE TITLE
Not An Issue : How to access private and protected members of Jasper object?

### ISSUE THREAD

**Issue by saurabhsonkar** [Jaspersoft/jasperreports#6]
I am using this library to create a Jasper object but the object which gets created has some private members in it like Static text element has “TEXT” field protected. 
However, I need to access the private or protected properties of these elements in some cases. 
Could you please guide me with this.

**Comment by teodord** [comment]
Hi,

Not sure which class you instantiate when you say you create a "Jasper object".
But if we are talking about creating report templates dynamically, using the API, then you should instantiate what we call "design" objects and are in the package which has JasperDesign at the top:

http://jasperreports.sourceforge.net/api/net/sf/jasperreports/engine/design/JasperDesign.html

In your case, a static text element would be represented by a JRDesignStaticText object, which has the setText(String) method:
http://jasperreports.sourceforge.net/api/net/sf/jasperreports/engine/design/JRDesignStaticText.html#setText(java.lang.String)

For more details, you can check the /demo/samples/noxmlreport sample shipped with the project distribution package, which is documented here:

http://jasperreports.sourceforge.net/sample.reference/noxmldesign/index.html

I hope this helps.
Teodor

P.S. Please ask your questions on the public forums at:
http://community.jaspersoft.com/answers

**Comment by saurabhsonkar** [comment]
Thanks for your concern.

I am creating Jasper object using jasperDesign class and initiating it using JRXmlLoader from jrxml file. 
I am extracting all the JRbands using getAllBands() method to get all JRbands and from each band, I am extracting JRelements using method getElements of JRband. However, after getting each element like static Field or text Field. I am not able to get their values from "TEXT" field which is private or protected.
Could you please me to access these values!
